apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Greeting Service
      port: 9090
      type: REST
      networkVisibility: Public
      context: /greeting
      schemaFilePath: openapi.yaml
    - name: Greeting Service2
      port: 9091
      type: GraphQL
      # networkVisibility: Organization
      context: /
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
      - name: choreo:///apifirst/mtGtm/mmvhKxd/ad088/v1.0/PUBLIC
        connectionConfig: 6d402ae3-925a-42F6-a62c-5a0bb94457dc
        env:
          - from: ServiceURL
            to: SERVICE_URL
      - name: thirdparty:/apifiXrst/mttm/mmvhxd/ad088/v1.0/PUBLIC
        connectionConfig: 6D402AE3-925A-42F6-A62C-5A0BB94458DC
        env:
          - from: ServiceURLK
            to: SERVICE_URL
          - from: ServiceURLk
            to: SERVICE_URL
      - name: database:/apifiXrst/mttm/mmvKhxd/ad088/v1.0/PUBLIC
        connectionConfig: 6D402AE3-925A-42F6-A62C-5A0BB94458DC
        env:
          - from: ServiceURLK
            to: SERVICE_URL
          - from: ServiceURLk
            to: SERVICE_URL
