openapi: 3.0.0
info:
  title: greeting_service_hz
  version: 1.0.0
servers:
  - url: /hz
paths:
  /welcome:
    get:
      summary: "Get welcome message"
      operationId: "getWelcome"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: string
