openapi: 3.0.0
info:
  title: hello_service
  version: 1.0.0
servers:
  - url: /hello
paths:
  /greeting:
    get:
      summary: "Get welcome message"
      operationId: "getWelcome"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: string
