openapi: "3.0.0"
info:
  title: Greeting Service
  version: 1.0.0
paths:
  /user:
    get:
      summary: welcome a person
      description: Greet a person by name
      tags:
        - greeting
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      deprecated: false
      security: []
